services:
  phone-calls:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phone-calls-service
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000
